//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoldCalculator.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MouldEntities : DbContext
    {
        public MouldEntities()
            : base("name=MouldEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Order> Orders { get; set; }
        public DbSet<Supplier> Suppliers { get; set; }
        public DbSet<ComponentShoe> ComponentShoes { get; set; }
        public DbSet<OffDay_Supplier_Mapping> OffDay_Supplier_Mappings { get; set; }
        public DbSet<OffDay> OffDays { get; set; }
        public DbSet<SizeRun> SizeRuns { get; set; }
        public DbSet<Mold> Molds { get; set; }
    }
}
